import sqlite3
from datetime import datetime

DEMO_BUYERS = [
    # ONION
    {
        "name": "Demo Onion Processing Hub - Nashik",
        "buyer_type": "Institutional Processor",
        "district": "Nashik",
        "state": "Maharashtra",
        "city": "Lasalgaon",
        "verified": True,
        "payment_reliability": 0.95,
        "demand_commodity": "Onion",
        "varieties": "Nasik Red, Garwa",
        "min_quantity": 20.0,
        "max_quantity": 800.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Export Quality",
        "indicative_price_min": 1950.0,
        "indicative_price_max": 2400.0,
        "offered_price": 2250.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Agro Wholesalers - Pune Market Yard",
        "buyer_type": "Wholesale Trader",
        "district": "Pune",
        "state": "Maharashtra",
        "city": "Pune",
        "verified": True,
        "payment_reliability": 0.92,
        "demand_commodity": "Onion",
        "varieties": "Red Onion, White Onion",
        "min_quantity": 10.0,
        "max_quantity": 500.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 1800.0,
        "indicative_price_max": 2300.0,
        "offered_price": 2150.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Dehydration Plant - Ahmednagar",
        "buyer_type": "Food Processor",
        "district": "Ahmednagar",
        "state": "Maharashtra",
        "city": "Ahilyanagar",
        "verified": True,
        "payment_reliability": 0.89,
        "demand_commodity": "Onion",
        "varieties": "White Onion, Red Onion",
        "min_quantity": 30.0,
        "max_quantity": 600.0,
        "accepted_grade": "Grade B",
        "quality_requirements": "Grade B, Grade C",
        "indicative_price_min": 1600.0,
        "indicative_price_max": 2000.0,
        "offered_price": 1850.0,
        "pickup_available": True,
        "delivery_available": False,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # TOMATO
    {
        "name": "Demo Fresh Retail Mart - Navi Mumbai",
        "buyer_type": "Retail Chain",
        "district": "Navi Mumbai",
        "state": "Maharashtra",
        "city": "Vashi",
        "verified": True,
        "payment_reliability": 0.98,
        "demand_commodity": "Tomato",
        "varieties": "Hybrid, Desi",
        "min_quantity": 10.0,
        "max_quantity": 350.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Firm Red",
        "indicative_price_min": 2400.0,
        "indicative_price_max": 3200.0,
        "offered_price": 2850.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Puree & Ketchup Works - Satara",
        "buyer_type": "Processor",
        "district": "Satara",
        "state": "Maharashtra",
        "city": "Satara",
        "verified": True,
        "payment_reliability": 0.90,
        "demand_commodity": "Tomato",
        "varieties": "Processing Hybrid",
        "min_quantity": 25.0,
        "max_quantity": 1000.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 2200.0,
        "indicative_price_max": 2900.0,
        "offered_price": 2600.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # POTATO
    {
        "name": "Demo Cold Storage & Chips - Kolhapur",
        "buyer_type": "Processor",
        "district": "Kolhapur",
        "state": "Maharashtra",
        "city": "Kolhapur",
        "verified": True,
        "payment_reliability": 0.94,
        "demand_commodity": "Potato",
        "varieties": "Kufri Jyoti, Chipsona",
        "min_quantity": 50.0,
        "max_quantity": 1200.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, High Starch",
        "indicative_price_min": 1400.0,
        "indicative_price_max": 1800.0,
        "offered_price": 1650.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Vegetable Mandi Syndicate - Solapur",
        "buyer_type": "Wholesale Trader",
        "district": "Solapur",
        "state": "Maharashtra",
        "city": "Solapur",
        "verified": True,
        "payment_reliability": 0.88,
        "demand_commodity": "Potato",
        "varieties": "Table Potato",
        "min_quantity": 20.0,
        "max_quantity": 500.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 1300.0,
        "indicative_price_max": 1700.0,
        "offered_price": 1500.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # WHEAT
    {
        "name": "Demo Flour Mill Corporation - Nagpur",
        "buyer_type": "Flour Miller",
        "district": "Nagpur",
        "state": "Maharashtra",
        "city": "Nagpur",
        "verified": True,
        "payment_reliability": 0.96,
        "demand_commodity": "Wheat",
        "varieties": "Sharbati, Lokwan",
        "min_quantity": 40.0,
        "max_quantity": 2000.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Clean Lustrous Grain",
        "indicative_price_min": 2400.0,
        "indicative_price_max": 2800.0,
        "offered_price": 2650.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Grain Consortium - Sangli",
        "buyer_type": "Institutional Aggregator",
        "district": "Sangli",
        "state": "Maharashtra",
        "city": "Sangli",
        "verified": True,
        "payment_reliability": 0.91,
        "demand_commodity": "Wheat",
        "varieties": "Lokwan, Tukdi",
        "min_quantity": 20.0,
        "max_quantity": 800.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 2350.0,
        "indicative_price_max": 2700.0,
        "offered_price": 2550.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # PADDY / RICE
    {
        "name": "Demo Rice Milling Industries - Bhandara & Nagpur",
        "buyer_type": "Rice Miller",
        "district": "Nagpur",
        "state": "Maharashtra",
        "city": "Nagpur",
        "verified": True,
        "payment_reliability": 0.95,
        "demand_commodity": "Paddy",
        "varieties": "Wada Kolam, Basmati",
        "min_quantity": 30.0,
        "max_quantity": 1500.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Low Moisture",
        "indicative_price_min": 2200.0,
        "indicative_price_max": 2850.0,
        "offered_price": 2500.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Coastal Paddy Buyers - Ratnagiri & Raigad",
        "buyer_type": "Aggregator",
        "district": "Ratnagiri",
        "state": "Maharashtra",
        "city": "Ratnagiri",
        "verified": True,
        "payment_reliability": 0.89,
        "demand_commodity": "Paddy",
        "varieties": "Ratna, Kolam",
        "min_quantity": 15.0,
        "max_quantity": 600.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 2100.0,
        "indicative_price_max": 2600.0,
        "offered_price": 2350.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # SOYBEAN
    {
        "name": "Demo Solvent Extraction Unit - Latur",
        "buyer_type": "Oilseed Processor",
        "district": "Latur",
        "state": "Maharashtra",
        "city": "Latur",
        "verified": True,
        "payment_reliability": 0.96,
        "demand_commodity": "Soybean",
        "varieties": "Yellow Soya (JS-335)",
        "min_quantity": 50.0,
        "max_quantity": 2500.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Oil Content > 18%",
        "indicative_price_min": 4300.0,
        "indicative_price_max": 4900.0,
        "offered_price": 4650.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Agro Oil Mill - Akola",
        "buyer_type": "Processor",
        "district": "Akola",
        "state": "Maharashtra",
        "city": "Akola",
        "verified": True,
        "payment_reliability": 0.92,
        "demand_commodity": "Soybean",
        "varieties": "Yellow Soya",
        "min_quantity": 30.0,
        "max_quantity": 1000.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Clean & Dry",
        "indicative_price_min": 4200.0,
        "indicative_price_max": 4750.0,
        "offered_price": 4500.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # BANANA
    {
        "name": "Demo Banana Ripening & Export - Jalgaon",
        "buyer_type": "Export Aggregator",
        "district": "Jalgaon",
        "state": "Maharashtra",
        "city": "Raver",
        "verified": True,
        "payment_reliability": 0.97,
        "demand_commodity": "Banana",
        "varieties": "Grand Naine (G9)",
        "min_quantity": 30.0,
        "max_quantity": 1500.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Export Uniform Bunch",
        "indicative_price_min": 1700.0,
        "indicative_price_max": 2400.0,
        "offered_price": 2100.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # GUAVA
    {
        "name": "Demo Fruit Pulp Works - Nashik",
        "buyer_type": "Pulp Processor",
        "district": "Nashik",
        "state": "Maharashtra",
        "city": "Nashik",
        "verified": True,
        "payment_reliability": 0.93,
        "demand_commodity": "Guava",
        "varieties": "Sardar (L-49), Taiwan Pink",
        "min_quantity": 15.0,
        "max_quantity": 600.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Blemish-free",
        "indicative_price_min": 2500.0,
        "indicative_price_max": 3500.0,
        "offered_price": 3100.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # ORANGE / MOSAMBI
    {
        "name": "Demo Nagpur Orange Packers - Nagpur",
        "buyer_type": "Packhouse & Exporter",
        "district": "Nagpur",
        "state": "Maharashtra",
        "city": "Nagpur",
        "verified": True,
        "payment_reliability": 0.96,
        "demand_commodity": "Orange",
        "varieties": "Nagpur Mandarin, Sweet Lime",
        "min_quantity": 25.0,
        "max_quantity": 1000.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Ripe Juice Quality",
        "indicative_price_min": 3200.0,
        "indicative_price_max": 4400.0,
        "offered_price": 3800.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
    {
        "name": "Demo Citrus Fresh Syndicate - Amravati",
        "buyer_type": "Wholesale Distributor",
        "district": "Amravati",
        "state": "Maharashtra",
        "city": "Amravati",
        "verified": True,
        "payment_reliability": 0.90,
        "demand_commodity": "Orange",
        "varieties": "Santra",
        "min_quantity": 20.0,
        "max_quantity": 800.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Grade B",
        "indicative_price_min": 2900.0,
        "indicative_price_max": 3900.0,
        "offered_price": 3400.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # BRINJAL / EGGPLANT
    {
        "name": "Demo Fresh Vegetable Syndicate - Pune",
        "buyer_type": "Vegetable Wholesaler",
        "district": "Pune",
        "state": "Maharashtra",
        "city": "Pune",
        "verified": True,
        "payment_reliability": 0.91,
        "demand_commodity": "Brinjal",
        "varieties": "Manjri Gota, Green Long",
        "min_quantity": 5.0,
        "max_quantity": 250.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Fresh Glossy Skin",
        "indicative_price_min": 1800.0,
        "indicative_price_max": 2600.0,
        "offered_price": 2200.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # GARLIC
    {
        "name": "Demo Spice & Garlic Wholesalers - Mumbai APMC",
        "buyer_type": "Spice Trader",
        "district": "Mumbai",
        "state": "Maharashtra",
        "city": "Navi Mumbai",
        "verified": True,
        "payment_reliability": 0.95,
        "demand_commodity": "Garlic",
        "varieties": "Ooty, Desi Garlic",
        "min_quantity": 10.0,
        "max_quantity": 400.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Dry Solid Cloves",
        "indicative_price_min": 8500.0,
        "indicative_price_max": 12000.0,
        "offered_price": 10500.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # GREEN CHILLI
    {
        "name": "Demo Chilli Pickles & Fresh Supply - Nanded",
        "buyer_type": "Processor & Trader",
        "district": "Nanded",
        "state": "Maharashtra",
        "city": "Nanded",
        "verified": True,
        "payment_reliability": 0.92,
        "demand_commodity": "Green Chilli",
        "varieties": "G4, Jwala",
        "min_quantity": 5.0,
        "max_quantity": 300.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Dark Green Crisp",
        "indicative_price_min": 3500.0,
        "indicative_price_max": 5200.0,
        "offered_price": 4300.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # MAIZE / CORN
    {
        "name": "Demo Poultry Feed Manufacturers - Sangli",
        "buyer_type": "Feed Processor",
        "district": "Sangli",
        "state": "Maharashtra",
        "city": "Miraj",
        "verified": True,
        "payment_reliability": 0.95,
        "demand_commodity": "Maize",
        "varieties": "Yellow Feed Corn",
        "min_quantity": 50.0,
        "max_quantity": 2000.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Moisture < 14%",
        "indicative_price_min": 2100.0,
        "indicative_price_max": 2550.0,
        "offered_price": 2350.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },

    # POMEGRANATE
    {
        "name": "Demo Solapur Pomegranate Exporters - Solapur",
        "buyer_type": "Export Aggregator",
        "district": "Solapur",
        "state": "Maharashtra",
        "city": "Pandharpur",
        "verified": True,
        "payment_reliability": 0.97,
        "demand_commodity": "Pomegranate",
        "varieties": "Bhagwa (Sindhuri)",
        "min_quantity": 15.0,
        "max_quantity": 600.0,
        "accepted_grade": "Grade A",
        "quality_requirements": "Grade A, Deep Red Arils",
        "indicative_price_min": 7500.0,
        "indicative_price_max": 11000.0,
        "offered_price": 9200.0,
        "pickup_available": True,
        "delivery_available": True,
        "payment_terms": "T+1 (24 hrs via KrishiChakra Escrow)",
        "verification_status": "Demo Verified Buyer",
        "contact_available": True,
        "is_demo": True,
    },
]


def update_db(db_path: str):
    con = sqlite3.connect(db_path)
    cur = con.cursor()

    # 1. Create mandi_deals table
    cur.execute("""
    CREATE TABLE IF NOT EXISTS mandi_deals (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        deal_id VARCHAR(60) UNIQUE,
        commodity VARCHAR(120),
        quantity FLOAT,
        market VARCHAR(160),
        price FLOAT,
        estimated_net_realization FLOAT,
        status VARCHAR(40) DEFAULT 'LOCKED',
        created_at DATETIME
    )
    """)

    # 2. Add columns to buyers table if missing
    cur.execute("PRAGMA table_info(buyers)")
    existing_cols = {row[1] for row in cur.fetchall()}
    needed_cols = [
        ("city", "VARCHAR(120)"),
        ("varieties", "VARCHAR(200)"),
        ("accepted_grade", "VARCHAR(100)"),
        ("indicative_price_min", "FLOAT"),
        ("indicative_price_max", "FLOAT"),
        ("pickup_available", "BOOLEAN DEFAULT 1"),
        ("delivery_available", "BOOLEAN DEFAULT 1"),
        ("payment_terms", "VARCHAR(120)"),
        ("verification_status", "VARCHAR(80)"),
        ("contact_available", "BOOLEAN DEFAULT 1"),
        ("is_demo", "BOOLEAN DEFAULT 1"),
    ]
    for col, ctype in needed_cols:
        if col not in existing_cols:
            cur.execute(f"ALTER TABLE buyers ADD COLUMN {col} {ctype}")
            print(f"Added column {col} to {db_path}")

    # 3. Seed demo buyers
    for b in DEMO_BUYERS:
        cur.execute("SELECT id FROM buyers WHERE name = ?", (b["name"],))
        row = cur.fetchone()
        if not row:
            cur.execute("""
            INSERT INTO buyers (
                name, buyer_type, district, state, city, verified,
                payment_reliability, demand_commodity, varieties, min_quantity,
                max_quantity, accepted_grade, quality_requirements, indicative_price_min,
                indicative_price_max, offered_price, pickup_available, delivery_available,
                payment_terms, verification_status, contact_available, is_demo, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                b["name"], b["buyer_type"], b["district"], b["state"], b["city"], 1 if b["verified"] else 0,
                b["payment_reliability"], b["demand_commodity"], b["varieties"], b["min_quantity"],
                b["max_quantity"], b["accepted_grade"], b["quality_requirements"], b["indicative_price_min"],
                b["indicative_price_max"], b["offered_price"], 1 if b["pickup_available"] else 0,
                1 if b["delivery_available"] else 0, b["payment_terms"], b["verification_status"],
                1 if b["contact_available"] else 0, 1 if b["is_demo"] else 0, datetime.utcnow()
            ))
            print(f"Seeded buyer: {b['name']} for {b['demand_commodity']}")

    con.commit()
    con.close()
    print(f"Completed migration & seeding for {db_path}")


if __name__ == "__main__":
    for p in ["backend_extracted/krishichakra.db", "krishichakra.db"]:
        update_db(p)
